on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - "a"
          - "b"
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: ${{ matrix.package }}
          repo-url: ${{ env.GITHUB_REPOSITORY }}
          monorepo-tags: true
